-- 코드를 입력하세요
SELECT DATE_FORMAT(DATETIME, '%H') as HOUR, COUNT(*) as COUNT
FROM ANIMAL_OUTS 
WHERE  DATE_FORMAT(DATETIME, '%H') >= '09'and DATE_FORMAT(DATETIME, '%H') <= '20'
GROUP BY HOUR
ORDER BY HOUR;