-- 코드를 작성해주세요
SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM SKILLCODES S
INNER JOIN DEVELOPERS D
    -- S.CODE 와 D.SKILL_CODE의 비트 AND 연산 결과가 S.CODE와 같다면 
    -- 해당 개발자는 그 스킬을 보유하고 있다. 
    ON (S.CODE & D.SKILL_CODE) = S.CODE
WHERE S.NAME IN('Python', 'C#')
ORDER BY D.ID ASC;
